baseURL = "https://tech-crunch2.netlify.com"
languageCode = "en-us"
paginate = 3
summaryLength = 0
theme = "rocinante"
title = "Don Quixote"
[author]
name = "Sid Verma"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokailight"
tabWidth = 2
[params]
about = "Hi. I'm **Don**. Some people also know me as Alonso Quixano.\n\nI ride around on my dear horse called _Rocinante_, being the best knight I can be. I named horse Rocinante because it's the best and the most powerful horse around.\n\n_If you see injustice around you, and need the help of an ingenious gentleman, feel free to reach out anytime. I'm usually always available._\n"
email = "email@example.com"
favicon = "/icon/favicon.jpg"
mainSections = ["post", "photos"]
[[params.links]]
[[params.links.link]]
href = "https://en.wikipedia.org/wiki/Don_Quixote"
name = "About"
new_tab = true
[[params.links.link]]
href = "/contact"
name = "Email"
smart_email_link = true
[[params.links]]
[[params.links.link]]
href = "https://www.goodreads.com/book/show/3836.Don_Quixote"
name = "Goodreads"
new_tab = true
[[params.links.link]]
href = "https://www.gutenberg.org/files/996/996-h/996-h.htm"
name = "Gutenberg"
new_tab = true
[[params.links.link]]
href = "https://twitter.com/search?q=%23twijote%20source%3Atwijote&src=typed_query&f=live"
name = "Twitter"
new_tab = true
[[params.links.link]]
href = "https://sidverma.io"
name = "Creator"
new_tab = true
